
REM Convert a "byte" file generated by the image2cpp utility to an imagae file
REM This script removes any comments, removes the 0X in front of each byte, removes commas, removes blanks
REM and finally converts the external hexadecimal to binary using xxd
grep -v %1.byte -e "//"   | sed -e "s/0x//g" | sed -e "s/, //g" | sed -e  "s/ //g" | xxd -r -ps > %1.img

